version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - shopnet

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/authdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - shopnet

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - shopnet

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    depends_on:
      - postgres-product
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-product:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"
    networks:
      - shopnet

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
    networks:
      - shopnet
  cart-service:
    build:
      context: ./cart-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres-cart
    networks:
      - backend

  postgres-cart:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cartdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"  # Changed host port to avoid conflict
    volumes:
      - cart_pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  cart_pgdata:

networks:
  backend:
  shopnet:
    driver: bridge
