server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/cart/**

      default-filters:
        - AddResponseHeader=X-Gateway, ShopSphere-Gateway
