server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates: [ Path=/auth/** ]
        - id: product-service
          uri: http://product-service:8082
          predicates: [ Path=/products/** ]
        - id: inventory-service
          uri: http://inventory-service:8084
          predicates: [ Path=/inventory/** ]
        - id: cart-service
          uri: http://cart-service:8083
          predicates: [ Path=/cart/** ]
        - id: order-service
          uri: http://order-service:8086
          predicates: [ Path=/orders/** ]
