spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://postgres-cart:5432/cartdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
server:
  port: 8083
