spring:
  datasource:
    url: jdbc:postgresql://cart-db:5432/cartdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: cart-service

server:
  port: 8083
